version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8888:80/tcp"
    environment:
      - WEBPASSWORD=12345678
      - DNSMASQ_USER=root
    volumes:
      - /volume1/docker/pihole/pihole:/etc/pihole/
      - /volume1/docker/pihole/dnsmasq.d:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped